import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

const AboutPage = () => {
  return (
    <>
    <Head>
      <title>AboutPage</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={`${styles.main} ${inter.className}`}>
      <div className={styles.description}>
        <p>
          ir a 
          <code className={styles.code}><a href='/'>Home</a></code>
        </p>
      </div>

    </main>
  </>
  )
}

export default AboutPage